# Generated by Django 5.2.3 on 2025-06-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categor_image',
            new_name='category_image',
        ),
    ]
