# Generated by Django 5.1.7 on 2025-05-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
